meross_email: "your_email@example.com"
meross_password: "your_password"
user_ip: "192.168.0.123"
presence_timeout: 1800 # seconds
light_states:
    - name: "Day"
      start: "09:30:00"
      end: "18:00:00"
      lights:
          - luminance: 100
            temperature: 100
          - luminance: 100
            temperature: 100
    - name: "Evening"
      start: "18:00:00"
      end: "23:30:00"
      lights:
          - rgb: [255, 139, 0]
          - rgb: [255, 45, 0]
    - name: "Before Bed"
      start: "23:30:00"
      end: "02:00:00"
      lights:
          - rgb: [179, 97, 0]
          - rgb: [179, 28, 0]
    - name: "Sleep"
      start: "02:00:00"
      end: "09:30:00"
      lights:
          - rgb: [0, 0, 0]
          - rgb: [0, 0, 0]
